# .github/labeler.yml
# maps path globs to labels for actions/labeler@v5
frontend:
  - changed-files:
      - any-glob-to-any-file: 'src/frontend/**'
backend:
  - changed-files:
      - any-glob-to-any-file: 'src/backend/**'
documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'
configuration:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
      - any-glob-to-any-file: '*.yml'
      - any-glob-to-any-file: '*.yaml'
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'tsconfig.json'
