# .github/labeler.yml
# put this file on the default branch (e.g., main) or in the PR branch
# maps path globs to labels
frontend:
  - 'src/frontend/**'
backend:
  - 'src/backend/**'
documentation:
  - 'docs/**'
