export const ROOM_CODE_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
export const ROOM_CODE_LENGTH = 4;
export const ROOM_CODE_PREFIX = 'CS';
export const ROOM_CODE_PATTERN = new RegExp(`^${ROOM_CODE_PREFIX}-[A-Z0-9]{${ROOM_CODE_LENGTH}}$`);
